name       : graphite2
version    : 1.3.11
release    : 5
source     :
    - https://github.com/silnrsi/graphite/releases/download/1.3.11/graphite2-1.3.11.tgz : bab92ed1844d6538e7e5bda76f6ac9aaf633e38b683983b942c78c8ce063ad7c
license    : LGPL-2.0
component  : xorg.fonts
summary    : Rendering engine for graphite fonts
description: |
    Rendering engine for graphite fonts
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig(python-2.7)
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-7999.patch
    libsuf="32"
    if [[ -z "${EMUL32BUILD}" ]]; then
        libsuf="64"
    fi
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DGRAPHITE2_COMPARE_RENDERER=OFF -DCMAKE_C_FLAGS:STRING="${CFLAGS}" -DLIB_SUFFIX="$libsuf" .
build      : |
    %make
install    : |
    %make_install
