name       : graphite2
version    : 1.3.13
release    : 6
source     :
    - https://github.com/silnrsi/graphite/releases/download/1.3.13/graphite2-1.3.13.tgz : dd63e169b0d3cf954b397c122551ab9343e0696fb2045e1b326db0202d875f06
license    : LGPL-2.1-or-later
component  : xorg.fonts
summary    : Rendering engine for graphite fonts
description: |
    Rendering engine for graphite fonts
builddeps  :
    - pkgconfig32(freetype2)
emul32     : yes
setup      : |
    %cmake . -DLIB_SUFFIX=%LIBSUFFIX% \
        -DGRAPHITE2_COMPARE_RENDERER=OFF \
        -DCMAKE_C_FLAGS:STRING="${CFLAGS}"
build      : |
    %make
install    : |
    %make_install
