name       : graphite2
version    : 1.3.10
release    : 4
source     :
    - https://github.com/silnrsi/graphite/releases/download/1.3.10/graphite2-1.3.10.tgz : 90fde3b2f9ea95d68ffb19278d07d9b8a7efa5ba0e413bebcea802ce05cda1ae
license    : LGPL-2.0
component  : xorg.fonts
summary    : Rendering engine for graphite fonts
description: |
    Rendering engine for graphite fonts
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig(python-2.7)
emul32     : yes
setup      : |
    libsuf="32"
    if [[ -z "${EMUL32BUILD}" ]]; then
        libsuf="64"
    fi
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DGRAPHITE2_COMPARE_RENDERER=OFF -DCMAKE_C_FLAGS:STRING="${CFLAGS}" -DLIB_SUFFIX="$libsuf" .
build      : |
    %make
install    : |
    %make_install
