name       : graphite2
version    : 1.3.9
release    : 3
source     :
    - https://heanet.dl.sourceforge.net/project/silgraphite/graphite2/graphite2-1.3.9.tgz : ec0185b663059553fd46e8c4a4f0dede60a02f13a7a1fefc2ce70332ea814567
license    : LGPL-2.0
component  : xorg.fonts
summary    : Rendering engine for graphite fonts
description: |
    Rendering engine for graphite fonts
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig32(freetype2)
    - pkgconfig(python-2.7)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    libsuf="32"
    if [[ -z "${EMUL32BUILD}" ]]; then
        libsuf="64"
    fi
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DGRAPHITE2_COMPARE_RENDERER=OFF -DCMAKE_C_FLAGS:STRING="${CFLAGS}" -DLIB_SUFFIX="$libsuf" .
build      : |
    %make
install    : |
    %make_install
