name       : graphite2
version    : 1.3
release    : 1
source     :
    - http://downloads.sourceforge.net/silgraphite/graphite2-1.3.3.tgz : 2f4b135adcd93bf9097cd20f66246a1e7ab8c2d8a76d8835a9035149e2de42d8
license    : LGPL-2.0
summary    : Rendering engine for graphite fonts
description: |
    Rendering engine for graphite fonts
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python-2.7)
setup      : |
    %cmake -DGRAPHITE2_COMPARE_RENDERER=OFF -DCMAKE_C_FLAGS:STRING="${CFLAGS}" .
build      : |
    %make
install    : |
    %make_install
